#!/usr/bin/env python
import os
import sys
import click
import traceback
from deploy import deploy
from monitor import monitor
from troubleshoot import troubleshoot
from scaleout import scaleout
from syncaddr import syncaddr
from stats import stats
from images import images
from vpc import vpc_show
from vpc import vpc_create
from wait import wait
from junos_config import junos_config
import logging
from botocore.exceptions import ClientError
from botocore.exceptions import NoCredentialsError
from util import error_msg

@click.group()
def cli():
    """vsrx-aws is an orchestration tool for automated provisioning,
       scaling and management of vSRX in AWS"""
    pass

cli.add_command(deploy)
cli.add_command(wait)
#cli.add_command(troubleshoot)
cli.add_command(stats)
cli.add_command(scaleout)
#cli.add_command(syncaddr, 'dyn-addr-sync')
cli.add_command(images)
cli.add_command(junos_config)
cli.add_command(vpc_show, 'vpc-show')
cli.add_command(vpc_create, 'vpc-create')
if __name__ == '__main__':
    try:
        cli()
    except NoCredentialsError:
        error_msg('Unable to locate credentials')
        error_msg('Please use "aws configure" to configure credentials or ' + \
                  'specify credential profile with "--profile"')
        sys.exit(2)
    except ClientError as e:
        error_msg(e)
        sys.exit(3)
